default_settings: null
behaviors:
  Elbow:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 0.001
      beta: 0.001
      epsilon: 0.1
      lambd: 0.9
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 10000
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 3
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
        learning_rate: 0.0003
        encoding_size: null
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 500000
    time_horizon: 32
    summary_freq: 5000
    threaded: false
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  timeout_wait: 60
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
  no_graphics_monitor: false
environment_parameters:
  my_environment_parameter:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1658
          value: 0.0
      name: MyFirstLesson
      completion_criteria:
        behavior: Elbow
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.2
        require_reset: false
    - value:
        sampler_type: uniform
        sampler_parameters:
          seed: 1659
          min_value: 2.0
          max_value: 5.0
      name: MySecondLesson
      completion_criteria:
        behavior: Elbow
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.4
        require_reset: true
    - value:
        sampler_type: uniform
        sampler_parameters:
          seed: 1660
          min_value: 5.0
          max_value: 8.0
      name: MyThirdLesson
      completion_criteria:
        behavior: Elbow
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.6
        require_reset: true
    - value:
        sampler_type: uniform
        sampler_parameters:
          seed: 1661
          min_value: 8.0
          max_value: 9.0
      name: MyFourthLesson
      completion_criteria:
        behavior: Elbow
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.8
        require_reset: true
checkpoint_settings:
  run_id: Elbow4
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
