behaviors:
  Elbow:
    trainer_type: ppo
    hyperparameters:
      batch_size: 8
      buffer_size: 64
      learning_rate: 1.0e-4
      learning_rate_schedule: linear
      
      beta: 1.0e-3
      epsilon: 0.1
      beta_schedule: linear
      epsilon_schedule: linear
      lambd: 0.9
      num_epoch: 5
      
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
      
        
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      
      curiosity:
        strength: 0.02
        gamma: 0.99
        learning_rate: 3.0e-4

    max_steps: 2.0e6
    time_horizon: 32
    summary_freq: 1000
    keep_checkpoints: 5
    checkpoint_interval: 10000
    threaded: false
    init_path: null
